# Limpiar Dataframe

In [1]:
# Importamos las librerías necesarias
import pandas as pd
import numpy as np

In [18]:
# Leemos el fichero CSV, especificando que el separador es ';'
df = pd.read_csv('datos.csv', sep = ';')

In [3]:
# Mostramos el Dataframe
df

   Nacional Comunidades y Ciudades Autónomas   Sexo  Periodo      Total
0     Total                     01 Andalucía  Total     2021  8.472.407
1     Total                        02 Aragón  Total     2021  1.326.261
2     Total       03 Asturias, Principado de  Total     2021  1.011.792
3     Total                04 Balears, Illes  Total     2021  1.173.008
4     Total                      05 Canarias  Total     2021  2.172.944
5     Total                     06 Cantabria  Total     2021    584.507
6     Total               07 Castilla y León  Total     2021  2.383.139
7     Total          08 Castilla - La Mancha  Total     2021  2.049.562
8     Total                      09 Cataluña  Total     2021  7.763.362
9     Total          10 Comunitat Valenciana  Total     2021  5.058.138
10    Total                   11 Extremadura  Total     2021  1.059.501
11    Total                       12 Galicia  Total     2021  2.695.645
12    Total          13 Madrid, Comunidad de  Total     2021  6.751.251
13    Total             14 Murcia, Región de  Total     2021  1.518.486
14    Total   15 Navarra, Comunidad Foral de  Total     2021    661.537
15    Total                    16 País Vasco  Total     2021  2.213.993
16    Total                     17 Rioja, La  Total     2021    319.796
17    Total                         18 Ceuta  Total     2021     83.517
18    Total                       19 Melilla  Total     2021     86.261

In [19]:
# Eliminamos las columnas 'Nacional' y 'Sexo'
df = df.drop(['Nacional','Sexo'], axis = 1)

In [16]:
# Mostramos el Dataframe
df

                      Comunidad  Periodo Poblacion
0                     Andalucía     2021   8472407
1                        Aragón     2021   1326261
2       Asturias, Principado de     2021   1011792
3                Balears, Illes     2021   1173008
4                      Canarias     2021   2172944
5                     Cantabria     2021    584507
6               Castilla y León     2021   2383139
7          Castilla - La Mancha     2021   2049562
8                      Cataluña     2021   7763362
9          Comunitat Valenciana     2021   5058138
10                  Extremadura     2021   1059501
11                      Galicia     2021   2695645
12         Madrid, Comunidad de     2021   6751251
13            Murcia, Región de     2021   1518486
14  Navarra, Comunidad Foral de     2021    661537
15                   País Vasco     2021   2213993
16                    Rioja, La     2021    319796
17                        Ceuta     2021     83517
18                      Melilla     2021     86261

In [24]:
# Renomabramos las columnas
df.rename(columns = {'Comunidades y Ciudades Autónomas':'Comunidad', 'Total':'Poblacion'}, inplace = True)

In [23]:
# Mostramos el Dataframe
df

                         Comunidad  Periodo  Poblacion
0                     01 Andalucía     2021  8.472.407
1                        02 Aragón     2021  1.326.261
2       03 Asturias, Principado de     2021  1.011.792
3                04 Balears, Illes     2021  1.173.008
4                      05 Canarias     2021  2.172.944
5                     06 Cantabria     2021    584.507
6               07 Castilla y León     2021  2.383.139
7          08 Castilla - La Mancha     2021  2.049.562
8                      09 Cataluña     2021  7.763.362
9          10 Comunitat Valenciana     2021  5.058.138
10                  11 Extremadura     2021  1.059.501
11                      12 Galicia     2021  2.695.645
12         13 Madrid, Comunidad de     2021  6.751.251
13            14 Murcia, Región de     2021  1.518.486
14  15 Navarra, Comunidad Foral de     2021    661.537
15                   16 País Vasco     2021  2.213.993
16                    17 Rioja, La     2021    319.796
17                        18 Ceuta     2021     83.517
18                      19 Melilla     2021     86.261

In [8]:
type(df['Comunidad'])

pandas.core.series.Series

In [9]:
# Eliminamos el código numérico de la columna 'Comunidad'
df['Comunidad'] = df['Comunidad'].str[3:]

In [25]:
# Mostramos el Dataframe
df

                         Comunidad  Periodo  Poblacion
0                     01 Andalucía     2021  8.472.407
1                        02 Aragón     2021  1.326.261
2       03 Asturias, Principado de     2021  1.011.792
3                04 Balears, Illes     2021  1.173.008
4                      05 Canarias     2021  2.172.944
5                     06 Cantabria     2021    584.507
6               07 Castilla y León     2021  2.383.139
7          08 Castilla - La Mancha     2021  2.049.562
8                      09 Cataluña     2021  7.763.362
9          10 Comunitat Valenciana     2021  5.058.138
10                  11 Extremadura     2021  1.059.501
11                      12 Galicia     2021  2.695.645
12         13 Madrid, Comunidad de     2021  6.751.251
13            14 Murcia, Región de     2021  1.518.486
14  15 Navarra, Comunidad Foral de     2021    661.537
15                   16 País Vasco     2021  2.213.993
16                    17 Rioja, La     2021    319.796
17                        18 Ceuta     2021     83.517
18                      19 Melilla     2021     86.261

In [11]:
# Eliminamos el separador de millares de la columna 'Población'
df['Poblacion'] = df['Poblacion'].str.replace('.', '', regex=False)

In [12]:
# Mostramos el Dataframe
df

                      Comunidad  Periodo Poblacion
0                     Andalucía     2021   8472407
1                        Aragón     2021   1326261
2       Asturias, Principado de     2021   1011792
3                Balears, Illes     2021   1173008
4                      Canarias     2021   2172944
5                     Cantabria     2021    584507
6               Castilla y León     2021   2383139
7          Castilla - La Mancha     2021   2049562
8                      Cataluña     2021   7763362
9          Comunitat Valenciana     2021   5058138
10                  Extremadura     2021   1059501
11                      Galicia     2021   2695645
12         Madrid, Comunidad de     2021   6751251
13            Murcia, Región de     2021   1518486
14  Navarra, Comunidad Foral de     2021    661537
15                   País Vasco     2021   2213993
16                    Rioja, La     2021    319796
17                        Ceuta     2021     83517
18                      Melilla     2021     86261

In [13]:
# Guardamos el Dataframe limpio en formato CSV
df.to_csv('datos_limpios.csv')